repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/flakeheaven/flakeheaven/
    rev: 3.3.0
    hooks:
      - id: flakeheaven

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-i", "--no-diff"]
      # UNCOMMENT IF NEEDED
      # - id: uncrustify
      # - id: clang-tidy
      # - id: oclint
      # - id: cppcheck
      # - id: cpplint
      # - id: include-what-you-use
