version: "3.5"

services:
  truck-jetson:
    container_name: truck-jetson
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck:jetson-0.5.0
    stdin_open: true
    privileged: true
    tty: true
    build:
      dockerfile: docker/truck-jetson.dockerfile
      context: .
    ports:
    - "2222:2222"
    - "9090:9090"
    volumes:
      - "${HOME}/truck:/truck"
      - /dev:/dev

  truck-amd64:
    container_name: truck-amd64
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck:amd64-0.5.0
    stdin_open: true
    tty: true
    build:
      dockerfile: docker/truck-amd64.dockerfile
      context: .
    ports:
    - "2222:2222"
    - "9090:9090"
    volumes:
      - "${HOME}/truck:/truck"
<<<<<<< HEAD
      - "/dev:/dev"
=======
      - /dev:/dev
>>>>>>> 7e10334 (add dev for amd64 container)
