version: "3.5"

services:
  truck-base-jetson:
    container_name: truck-base
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck-base:jetson-0.2.0
    runtime: nvidia
    stdin_open: true
    tty: true
    build:
      dockerfile: docker/truck-base-jetson.dockerfile
      context: .
    ports:
    - "9090:9090"
    volumes:
    - "/dev:/dev"

  truck-base-amd64:
    container_name: truck-base
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck-base:amd64-0.2.0
    stdin_open: true
    tty: true
    build:
      dockerfile: docker/truck-base-amd64.dockerfile
      context: .
    ports:
    - "9090:9090"
