version: "3.5"

services:
  truck-jetson:
    container_name: truck-jetson
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck:jetson-0.5.2
    stdin_open: true
    privileged: true
    tty: true
    build:
      dockerfile: docker/truck-jetson.dockerfile
      context: .
    ports:
    - "2222:2222"
    - "8080:8080"
    - "9090:9090"
    volumes:
      - "${PWD}:/truck"
      - "/dev:/dev"

  truck-amd64:
    container_name: truck-amd64
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/truck:amd64-0.5.2
    stdin_open: true
    privileged: true
    tty: true
    build:
      dockerfile: docker/truck-amd64.dockerfile
      context: .
    ports:
    - "2222:2222"
    - "8080:8080"
    - "9090:9090"
    volumes:
      - "${PWD}:/truck"
      - "/dev:/dev"
