version: "3"

services:
  truck:
    container_name: "${CONTAINER_NAME:-truck-example}"
    image: "hexwhyzet/diploma-thesis:latest"
    privileged: true
    runtime: "${DOCKER_RUNTIME:-runc}"
    ports:
      - "${FOXGLOVE_PORT:-8765}:8765"
      - "${VIDEO_STREAMING_PORT:-8889}:8889"
      - "${GAZEBO_PORT:-11345}:11345"
    volumes:
      - ".:/truck"
      - "/dev:/dev"

networks:
  default:
    name: "${CONTAINER_NAME:-truck-example}"
