---
- name: Build ros packages
  hosts: 127.0.0.1
  connection: local

  tags:
    - never
    - build
  
  tasks:
    - name: Build planning_node
      shell: colcon build --packages-up-to planning_node
      args:
        chdir: packages
    
    - name: Build unwrapping_node
      shell: colcon build --packages-up-to unwrapping_node
      args:
        chdir: packages

- name: Start ros packages
  hosts: 127.0.0.1
  connection: local

  tags:
    - never
    - start

  tasks:
    - name: Create log dir
      file:
        name: log
        state: directory

    - name: Start planning node
      shell: |
        . packages/install/setup.bash
        ros2 run planning_node node >> log/planning_node.log 2>&1 &
        echo "$!" > log/planning_node.pid
        disown -h "$(cat log/planning_node.pid)"
      args:
        executable: /bin/bash

    - name: Start unwrapping node
      shell: |
        . packages/install/setup.bash
        ros2 run unwrapping_node node >> log/unwrapping_node.log 2>&1 &
        echo "$!" > log/unwrapping_node.pid
        disown -h "$(cat log/unwrapping_node.pid)"
      args:
        executable: /bin/bash

    - name: Start rosbridge_server
      shell: |
        . packages/install/setup.bash
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml >>log/rosbridge_server.log 2>&1 &
        echo "$!" > log/rosbridge_server.pid
        disown -h "$(cat log/rosbridge_server.pid)"
      args:
        executable: /bin/bash

- name: Stop ros packages
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Stop planning node
      shell: |
        kill "$(cat log/planning_node.pid)"
      args:
        executable: /bin/bash

    - name: Stop unwrapping node
      shell: |
        kill "$(cat log/unwrapping_node.pid)"
      args:
        executable: /bin/bash

    - name: Stop rosbridge_server
      shell: |
        kill "$(cat log/rosbridge_server.pid)"
      args:
        executable: /bin/bash

  tags:
    - never
    - stop