readingDataPointsFilters:
  - RandomSamplingDataPointsFilter: 
      prob: 0.7 # 70% данных будут случайно выбраны
      seed: 42

referenceDataPointsFilters: # Секция которая применяется к целевым облакам
  - SamplingSurfaceNormalDataPointsFilter:
      knn: 10 # Количество ближайших соседей для выборки нормалей поверхности

  - ObservationDirectionDataPointsFilter: 
      x: 0.0
      y: 0.0
      z: 0.0
      
  - OrientNormalsDataPointsFilter: 
      towardCenter: 1

matcher:
  KDTreeMatcher:
    knn: 1 # Количество ближайших соседей для сопоставления (будет найден только один ближайший сосед)
    epsilon: 2 # Учет ошибки

# outlierFilters:
#   - MaxDistOutlierFilter:
#       maxDist: 30 # Максимальное расстояние от точки до ближайшей точки в облаке. Точки, которые находятся дальше maxDist, будут считаться выбросами.

#   - MedianDistOutlierFilter:
#       factor: 30 # Умножитель для медианного расстояния. Точки, которые находятся дальше factor * медианное расстояние, будут отфильтрованы как выбросы.

#   - MinDistOutlierFilter:
#       minDist: 0.01  # Минимальное расстояние до ближайшей точки. Точки, которые находятся ближе minDist, будут считаться выбросами.

errorMinimizer:
  PointToPlaneErrorMinimizer:
   force2D: 1 # Так как все облака находятся в одной плоскости

transformationCheckers: # Фильтр оценивает, насколько сильно изменились параметры трансформации
  - CounterTransformationChecker:
      maxIterationCount: 50 # Максимальное количество итераций для проверки преобразования

  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001 # Минимальная допустимая ошибка вращения для проверки преобразования
      minDiffTransErr: 0.001 # Минимальная допустимая ошибка трансляции для проверки преобразования
      smoothLength: 4 # При оценке изменений будут учитываться последние 4 итерации

logger:
   FileLogger: 