readingDataPointsFilters:
   - IdentityDataPointsFilter

referenceDataPointsFilters: # Секция которая применяется к целевым облакам
  - RandomSamplingDataPointsFilter:
      prob: 0.8  # 80% данных будут случайно выбраны
      seed: 42
      randomSamplingMethod: 1

  - SurfaceNormalDataPointsFilter:
      knn: 50
      epsilon: 0.0
      keepNormals: 1
      keepDensities: 0
      keepEigenValues: 0
      keepEigenVectors: 0
      keepMatchedIds: 0

  - ObservationDirectionDataPointsFilter:
      x: 0.0
      y: 0.0
      z: 0.0

  - OrientNormalsDataPointsFilter:
      towardCenter: 1

  - ObservationDirectionDataPointsFilter:
      x: 0.0
      y: 0.0
      z: 0.0


matcher:
 KDTreeMatcher

outlierFilters:
   - NullOutlierFilter

errorMinimizer:
   IdentityErrorMinimizer

transformationCheckers:
   - CounterTransformationChecker

inspector:
   NullInspector

logger:
   NullLogger