shape:
  length: 0.505           # m
  width: 0.313            # m
  base_to_rear: 0.2525    # m
  circles_count: 5        # qnt

wheel_base:
  length: 0.405           # m
  width: 0.213            # m
  base_to_rear: 0.2025    # m

wheel:
  radius: 0.0525          # m
  width: 0.058            # m

lidar:
  from_base: { x: 0.0, y: 0.0 } # m
  angle_min: 0.0                # deg
  angle_max: 360.0              # deg
  angle_increment: 0.1125       # deg
  range_min: 0.0                # m
  range_max: 25.0               # m

limits:
  steering: { inner: 40.0, outer: 40.0 } # deg
  max_abs_curvature: 2.0                 # 1/m
  steering_velocity: 2.0                 # rad/s
  velocity: { min: -0.5, max: +0.8 }     # m/s
  max_acceleration: 1.0                  # m/s^2
  max_deceleration: 2.0                  # m/s^2

# Motor to differential ratio. See docs/gearbox.md for more info.
gear_ratio: 0.08421
servo_home_angles: {left: 89, right: 96}  # deg