readingDataPointsFilters: # Секция, которая применяется к входным облакам
  - RandomSamplingDataPointsFilter: 
      prob: 0.7  # 70% данных будут случайно выбраны
      seed: 42

referenceDataPointsFilters: # Секция которая применяется к целевым облакам
  - SamplingSurfaceNormalDataPointsFilter:
      knn: 10   # Количество ближайших соседей для выборки нормалей поверхности

matcher:
  KDTreeMatcher:
    knn: 1                # Количество ближайших соседей для сопоставления (будет найден только один ближайший сосед)
    epsilon: 2            # Учет ошибки

errorMinimizer:
  PointToPlaneErrorMinimizer:
   force2D: 1            # Так как все облака находятся в одной плоскости

transformationCheckers: # Фильтр оценивает, насколько сильно изменились параметры трансформации
  - CounterTransformationChecker:
      maxIterationCount: 50  # Максимальное количество итераций для проверки преобразования

  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001   # Минимальная допустимая ошибка вращения для проверки преобразования
      minDiffTransErr: 0.001   # Минимальная допустимая ошибка трансляции для проверки преобразования
      smoothLength: 4          # При оценке изменений будут учитываться последние 4 итерации

inspector:
  VTKFileInspector:
     baseFileName : packages/icp_test/inspector/icp_test
     dumpDataLinks : 1          # Флаг для сохранения ссылок на данные
     dumpReading : 1            # Флаг для сохранения данных чтения
     dumpReference : 1          # Флаг для сохранения эталонных данных

logger:
   FileLogger: 
