readingDataPointsFilters:
  - RandomSamplingDataPointsFilter:  # Фильтр для случайной выборки точек из облака.
      prob: 0.7  # Вероятность выборки каждой точки; 0.5 означает, что половина точек будет выбрана.

referenceDataPointsFilters:
  - SamplingSurfaceNormalDataPointsFilter:  # Фильтр для выборки точек на основе нормалей к поверхности.
      knn: 10  # Количество ближайших соседей для оценки нормалей; используется для улучшения качества выборки.

matcher:
  KDTreeMatcher:  # Алгоритм сопоставления, использующий KD-дерево для поиска ближайших точек.
    knn: 1  # Количество ближайших соседей для поиска; 1 означает, что будет искаться только ближайшая точка.
    epsilon: 2  # Допустимое расстояние для сопоставления; контролирует, насколько близко должны находиться точки.

outlierFilters:
   - TrimmedDistOutlierFilter:  # Фильтр для удаления выбросов на основе расстояний.
      ratio: 0.85  # Доля точек, которая будет оставлена после фильтрации; 0.85 означает, что 85% наиболее близких точек будут сохранены.
   - RobustOutlierFilter:  # Фильтр для удаления выбросов, основанный на методах устойчивости.
      distanceType: point2plane  # Тип расстояния для определения выбросов; point2plane учитывает расстояние от точки до плоскости.

errorMinimizer:
  PointToPlaneErrorMinimizer: # Минимизатор ошибки, использующий метод "точка-к-плоскости".
   force2D: 0
   # Этот метод обычно более устойчив к шуму и позволяет лучше учитывать геометрию облаков.

transformationCheckers:
  - CounterTransformationChecker:  # Проверка трансформаций по количеству итераций.
      maxIterationCount: 50  # Максимальное количество итераций для алгоритма ICP; предотвращает бесконечные циклы.
  - DifferentialTransformationChecker:  # Проверка трансформаций на основе разностей.
      minDiffRotErr: 0.001  # Минимальная допустимая ошибка вращения; если ошибка меньше, итерация останавливается.
      minDiffTransErr: 0.01  # Минимальная допустимая ошибка трансляции; аналогично для трансляции.
      smoothLength: 4  # Длина сглаживания для оценки изменений; помогает избежать ложных срабатываний.

inspector:
   NullInspector
#  VTKFileInspector:  # Инспектор для визуализации и анализа данных с использованием VTK.
#      baseFileName: pointmatcher-run1  # Базовое имя файла для сохранения результатов инспекции.
#      dumpPerfOnExit: 0  # Сохранять ли производительность при выходе (0 - не сохранять).
#      dumpStats: 0  # Сохранять ли статистику (0 - не сохранять).
#      dumpIterationInfo: 1  # Сохранять ли информацию об итерациях (1 - сохранять).
#      dumpDataLinks: 0  # Сохранять ли ссылки на данные (0 - не сохранять).
#      dumpReading: 0  # Сохранять ли данные чтения (0 - не сохранять).
#      dumpReference: 0  # Сохранять ли эталонные данные (0 - не сохранять).

logger:
   FileLogger:  # Логгер для записи информации в файл.
   # Позволяет отслеживать процесс выполнения и отладку алгоритма.